In [12]:
import pandas as pd
from os import listdir
from os.path import join
import json

In [13]:
COMPRESSED_FOLDER_PATH = join("../.outFiles/analysis/compressed")

LIST_FP = join("../.outFiles/congress_members/list.json")
politicians_df = pd.read_json(LIST_FP)
politicians_df

,heading,name,chamber,state,district,party,served
0,MEMBER,"Abraham, Ralph Lee",Representative,Louisiana,5,Republican,"[""House: 2015-2021""]"
1,MEMBER,"Adams, Alma S.",Representative,North Carolina,12,Democratic,"[""House: 2014-Present""]"
2,MEMBER,"Aderholt, Robert B.",Representative,Alabama,4,Republican,"[""House: 1997-Present""]"
3,MEMBER,"Aguilar, Pete",Representative,California,33,Democratic,"[""House: 2015-Present""]"
4,MEMBER,"Alexander, Lamar",Senator,Tennessee,,Republican,"[""Senate: 2003-2021""]"
...,...,...,...,...,...,...,...
958,MEMBER,"Young, David",Representative,Iowa,3,Republican,"[""House: 2015-2019""]"
959,MEMBER,"Young, Don",Representative,Alaska,At Large,Republican,"[""House: 1973-2022""]"
960,MEMBER,"Young, Todd",Senator,Indiana,,Republican,"[""Senate: 2017-Present"",""House: 2011-2017""]"
961,MEMBER,"Zeldin, Lee M.",Representative,New York,1,Republican,"[""House: 2015-2023""]"
962,MEMBER,"Zinke, Ryan K.",Representative,Montana,1,Republican,"[""House: 2015-2017, 2023-Present""]"

In [14]:
politicians_df = politicians_df.drop(columns=["heading", "served"])
politicians_df.columns = [
    "p_full_name",
    "p_chamber",
    "p_state",
    "p_district",
    "p_party",
]

politicians_df["p_party"] = politicians_df["p_party"].str.slice(0,1)
politicians_df["p_chamber"] = politicians_df["p_chamber"].str.slice(0,1)

def fix_name(in_name: str):
    if "," in in_name:
        tmp = in_name.split(",")
        in_name = tmp[1] + " " + tmp[0]
    
    in_name = in_name.replace(".","")
    return in_name

politicians_df["p_full_name"] = politicians_df["p_full_name"].apply(fix_name) 

save_path = join(COMPRESSED_FOLDER_PATH, "politician.csv")
politicians_df.to_csv(save_path, index=False, header=True)


politicians_df

,p_full_name,p_chamber,p_state,p_district,p_party,p_years_served
0,Ralph Lee Abraham,R,Louisiana,5,R,2015-2021
1,Alma S Adams,R,North Carolina,12,D,2014-Present
2,Robert B Aderholt,R,Alabama,4,R,1997-Present
3,Pete Aguilar,R,California,33,D,2015-Present
4,Lamar Alexander,S,Tennessee,,R,2003-2021
...,...,...,...,...,...,...
958,David Young,R,Iowa,3,R,2015-2019
959,Don Young,R,Alaska,At Large,R,1973-2022
960,Todd Young,S,Indiana,,R,2017-Present
961,Lee M Zeldin,R,New York,1,R,2015-2023
962,Ryan K Zinke,R,Montana,1,R,"2015-2017, 2023-Present"